"""campo destacado en productos

Revision ID: 12b08351f5fe
Revises: 4e73451ddd5e
Create Date: 2026-03-24 13:31:08.519710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12b08351f5fe'
down_revision = '4e73451ddd5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destacado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('destacado')

    # ### end Alembic commands ###
