"""constraints e indices en cart_items, order_items y orders

Revision ID: 4b59fd0d695b
Revises: a1b2c3d4e5f6
Create Date: 2026-06-18 09:27:06.897698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b59fd0d695b'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cart_items_cart_id'), ['cart_id'], unique=False)
        batch_op.create_index('uq_cart_item_cart_product_no_size', ['cart_id', 'product_id'], unique=True, postgresql_where=sa.text('size IS NULL'))
        batch_op.create_unique_constraint('uq_cart_item_cart_product_size', ['cart_id', 'product_id', 'size'])

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint('uq_cart_item_cart_product_size', type_='unique')
        batch_op.drop_index('uq_cart_item_cart_product_no_size', postgresql_where=sa.text('size IS NULL'))
        batch_op.drop_index(batch_op.f('ix_cart_items_cart_id'))

    # ### end Alembic commands ###
