"""tallas y numero de item en producto

Revision ID: 4e73451ddd5e
Revises: e48a677b4592
Create Date: 2026-03-24 10:09:10.790701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e73451ddd5e'
down_revision = 'e48a677b4592'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sizes', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('item_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('item_number')
        batch_op.drop_column('sizes')

    # ### end Alembic commands ###
