"""add esencial to products

Revision ID: 955f2f809ce7
Revises: 6f9e864263a9
Create Date: 2026-03-28 14:24:53.959603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955f2f809ce7'
down_revision = '6f9e864263a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('esencial', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('esencial')

    # ### end Alembic commands ###
