"""add position accent_word btn2_text to banners

Revision ID: d93dafa3b698
Revises: 12b08351f5fe
Create Date: 2026-03-26 14:06:17.093710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd93dafa3b698'
down_revision = '12b08351f5fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('accent_word', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('btn2_text', sa.String(length=60), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('btn2_text')
        batch_op.drop_column('accent_word')
        batch_op.drop_column('position')

    # ### end Alembic commands ###
